services:
  lengow-test-db:
    container_name: lengow-test-db
    image: postgres:16
    volumes:
      - technical-db-data:/var/lib/postgresql/data/
      - ./scripts:/scripts/
    env_file:
      - ./app.env
    ports:
      - "5432:5432"

volumes:
  technical-db-data:
